"""Independent acceptance tests: enumerate tiny schedules, not solver internals.

The oracle below deliberately does not call ShopShift's validator or OR-Tools.
It checks elapsed UTC time and pairwise occupancy directly, including every
integer start in each small horizon. Large benchmark fixtures are generated by
scripts/benchmark_shop.py instead of checked into the repository.
"""

from __future__ import annotations

import copy
import csv
import itertools
import os
import random
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest

from shopshift.importing import ImportProblem, import_operations, read_table
from shopshift.model import Operation, Placement, Project, Resource, Scenario, Window
from shopshift.solver import suggest
from shopshift.storage import (
    StorageProblem,
    export_csv,
    export_html,
    load_project,
    restore_project,
    save_project,
)
from shopshift.timeutil import format_timestamp, parse_timestamp, working_windows
from shopshift.validator import validate


def independent_feasible(project, starts, respect_locks=False):
    """Small oracle for well-formed inputs, independent of production helpers."""
    if set(starts) != set(project.operations):
        return False
    for identity, op in project.operations.items():
        start, end = starts[identity], starts[identity] + op.setup + op.run
        if start < project.horizon_start or end > project.horizon_end:
            return False
        if op.release is not None and start < op.release:
            return False
        for resource in [project.machines[op.machine]] + (
            [project.operators[op.operator]] if op.operator else []
        ):
            # Test inputs use disjoint, nonadjacent windows so containment is
            # unambiguous and independent of calendar normalization policy.
            if not any(window.start <= start and end <= window.end for window in resource.windows):
                return False
        for predecessor in op.predecessors:
            pred = project.operations[predecessor]
            if start < starts[predecessor] + pred.setup + pred.run:
                return False
        existing = project.scenario.placements.get(identity)
        if respect_locks and existing and existing.locked and start != existing.start:
            return False
    for left, right in itertools.combinations(project.operations.values(), 2):
        if left.machine == right.machine or (left.operator and left.operator == right.operator):
            left_end = starts[left.id] + left.setup + left.run
            right_end = starts[right.id] + right.setup + right.run
            if starts[left.id] < right_end and starts[right.id] < left_end:
                return False
    return True


def objective(project, starts):
    ends = {key: starts[key] + op.setup + op.run for key, op in project.operations.items()}
    return max(ends.values()) - project.horizon_start + sum(
        max(0, ends[key] - op.due) for key, op in project.operations.items() if op.due is not None
    )


def all_starts(project):
    ids = tuple(project.operations)
    for values in itertools.product(range(project.horizon_start, project.horizon_end + 1), repeat=len(ids)):
        yield dict(zip(ids, values, strict=True))


def tiny_shop(seed):
    rng = random.Random(seed)
    windows = [[Window(0, 6)], [Window(0, 2), Window(3, 6)], [Window(1, 6)]]
    project = Project(horizon_start=0, horizon_end=6)
    project.machines = {f"m{i}": Resource(f"m{i}", copy.deepcopy(rng.choice(windows))) for i in range(2)}
    project.operators = {"o0": Resource("o0", copy.deepcopy(rng.choice(windows)))}
    for index in range(3):
        key = f"op{index}"
        project.operations[key] = Operation(
            key, "job", f"m{rng.randrange(2)}", "o0" if rng.random() < 0.5 else "",
            setup=1 if rng.random() < 0.3 else 0, run=rng.randint(1, 2),
            predecessors=[f"op{index - 1}"] if index and rng.random() < 0.45 else [],
            release=rng.choice([None, 0, 1]), due=rng.choice([None, 3, 5]),
        )
    return project


@pytest.mark.parametrize("seed", range(16))
def test_validator_agrees_with_exhaustive_independent_oracle(seed):
    project = tiny_shop(seed)
    for starts in all_starts(project):
        scenario = Scenario("Candidate", {key: Placement(value) for key, value in starts.items()})
        actual = not any(issue.severity == "error" for issue in validate(project, scenario))
        assert actual == independent_feasible(project, starts), (seed, starts, validate(project, scenario))


@pytest.mark.parametrize("seed", range(24))
def test_solver_feasibility_and_objective_match_exhaustive_oracle(seed):
    project = tiny_shop(seed)
    if seed % 3 == 0:
        project.scenario.placements["op0"] = Placement(seed % 5, locked=True)
    before = copy.deepcopy(project.to_dict())
    admissible = [starts for starts in all_starts(project) if independent_feasible(project, starts, True)]
    result = suggest(project, time_limit=1)
    assert project.to_dict() == before, "Suggestions must not mutate the project"
    if not admissible:
        assert result.status in {"infeasible", "invalid"}, (seed, result)
        assert not result.placements
    else:
        assert result.status == "optimal", (seed, result)
        starts = {key: value.start for key, value in result.placements.items()}
        assert independent_feasible(project, starts, True)
        expected = min(objective(project, candidate) for candidate in admissible)
        assert objective(project, starts) == expected, (seed, expected, result)
        assert result.objective == pytest.approx(expected)
        for key, placement in project.scenario.placements.items():
            if placement.locked:
                assert result.placements[key] == placement


def test_operator_calendar_and_resource_overlap_are_independent_of_machine():
    project = Project(horizon_start=0, horizon_end=12)
    project.machines = {key: Resource(key, [Window(0, 12)]) for key in ("lathe", "mill")}
    project.operators = {"operator": Resource("operator", [Window(0, 5), Window(7, 12)])}
    project.operations = {
        "a": Operation("a", "A", "lathe", "operator", run=4),
        "b": Operation("b", "B", "mill", "operator", run=4),
    }
    for starts, expected in [({"a": 0, "b": 7}, True), ({"a": 0, "b": 3}, False),
                             ({"a": 2, "b": 7}, False), ({"a": 0, "b": 8}, True)]:
        scenario = Scenario("Candidate", {key: Placement(value) for key, value in starts.items()})
        assert independent_feasible(project, starts) == expected
        assert (not any(i.severity == "error" for i in validate(project, scenario))) == expected


def test_unlocked_bad_schedule_can_be_rebuilt_but_locked_conflict_cannot():
    project = Project(horizon_start=0, horizon_end=10,
                      machines={"m": Resource("m", [Window(0, 10)])}, operations={
                          "a": Operation("a", "J", "m", run=4),
                          "b": Operation("b", "J", "m", run=4),
                      })
    project.scenario.placements = {"a": Placement(-2), "b": Placement(0)}
    result = suggest(project, time_limit=1)
    assert result.status == "optimal"
    assert independent_feasible(project, {key: value.start for key, value in result.placements.items()})
    project.scenario.placements = {"a": Placement(0, True), "b": Placement(1, True)}
    result = suggest(project, time_limit=1)
    assert result.status in {"invalid", "infeasible"}
    assert not result.placements
    assert result.issues


@pytest.mark.parametrize("mutation", ["missing_machine", "missing_operator", "missing_predecessor", "cycle"])
def test_partial_or_invalid_inputs_never_produce_commit_ready_suggestion(mutation):
    project = tiny_shop(2)
    if mutation == "missing_machine":
        project.operations["op0"].machine = "unknown"
    elif mutation == "missing_operator":
        project.operations["op0"].operator = "unknown"
    elif mutation == "missing_predecessor":
        project.operations["op0"].predecessors = ["unknown"]
    else:
        project.operations["op0"].predecessors = ["op2"]
        project.operations["op2"].predecessors = ["op0"]
    result = suggest(project, time_limit=1)
    assert result.status == "invalid"
    assert result.issues and not result.placements


def test_actual_time_limited_search_does_not_claim_infeasibility():
    project = Project(horizon_start=0, horizon_end=1000,
                      machines={"m": Resource("m", [Window(0, 1000)])})
    project.operations = {str(i): Operation(str(i), "J", "m", run=10) for i in range(30)}
    # The arithmetic witness proves feasibility independently, even when a
    # deliberate tiny search budget expires before CP-SAT constructs a plan.
    witness = {str(i): i * 10 for i in range(30)}
    assert independent_feasible(project, witness)
    result = suggest(project, time_limit=1e-9)
    assert result.status == "time_limited"
    assert not result.placements and result.objective is None


@pytest.mark.parametrize("value,zone", [
    ("2026-03-08T02:30", "America/New_York"),
    ("2026-11-01T01:30", "America/New_York"),
    ("2026-10-04T02:15", "Australia/Lord_Howe"),
    ("2026-04-05T01:45", "Australia/Lord_Howe"),
    ("2026-01-01T10:00:00.5Z", "UTC"),
    ("2026-01-01T10:00+01:75", "UTC"),
    ("0001-01-01T00:00+23:59", "UTC"),
    ("9999-12-31T23:59-23:59", "UTC"),
])
def test_dates_never_guess_dst_or_round_subsecond_inputs(value, zone):
    with pytest.raises(ValueError):
        parse_timestamp(value, zone)


def test_dst_fold_offsets_represent_distinct_instants_and_roundtrip():
    first = parse_timestamp("2026-11-01T01:30-04:00", "America/New_York")
    second = parse_timestamp("2026-11-01T01:30-05:00", "America/New_York")
    assert second - first == 3600
    assert parse_timestamp(format_timestamp(first, "America/New_York"), "America/New_York") == first
    assert parse_timestamp(format_timestamp(second, "America/New_York"), "America/New_York") == second
    project = Project(timezone="America/New_York", horizon_start=first, horizon_end=second + 3600,
                      machines={"night": Resource("night", [Window(first, second + 3600)])},
                      operations={"a": Operation("a", "J", "night", run=5400)})
    project.scenario.placements["a"] = Placement(first, True)
    assert not [i for i in validate(project) if i.severity == "error"]
    assert suggest(project, time_limit=1).placements["a"].start == first


def test_overnight_weekday_shift_is_clipped_and_includes_saturday_morning():
    # Friday's shift remains available into Saturday, even though Saturday
    # itself does not start a weekday shift. The expected instants use stdlib.
    start = int(datetime(2026, 10, 9, 21, tzinfo=timezone.utc).timestamp())
    end = int(datetime(2026, 10, 10, 5, tzinfo=timezone.utc).timestamp())
    windows = working_windows(start, end, "Europe/Berlin", 22, 6)
    assert [(w.start, w.end) for w in windows] == [(start, end - 3600)]


def _write_csv(path, rows, headers=("Op", "Job", "Machine", "Run")):
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.writer(handle)
        writer.writerow(headers)
        writer.writerows(rows)


MAPPING = {"id": "Op", "job": "Job", "machine": "Machine", "run": "Run"}


def import_project():
    start = parse_timestamp("2026-10-05T08:00Z", "UTC")
    return Project(horizon_start=start, horizon_end=start + 7 * 86400)


def test_reimport_preserves_all_scenario_decisions_and_exposes_changed_duration(tmp_path):
    path = tmp_path / "erp.csv"
    _write_csv(path, [["a", "J", "mill", "60"], ["b", "J", "mill", "60"]])
    first = import_operations(import_project(), path, MAPPING).project
    start = first.horizon_start
    first.scenario.placements = {"a": Placement(start, True), "b": Placement(start + 3600)}
    first.scenarios["Alternative"] = Scenario("Alternative", {"a": Placement(start + 86400, True)})
    original = copy.deepcopy(first.to_dict())
    _write_csv(path, [["a", "J", "mill", "90"], ["c", "J", "lathe", "30"]])
    second = import_operations(first, path, first.mappings["__last__"])
    assert first.to_dict() == original
    assert second.added == ["c"] and second.updated == ["a"] and second.retained == ["b"]
    assert second.project.scenarios == first.scenarios
    assert second.project.operations["a"].duration == 5400
    assert second.project.operations["b"] == first.operations["b"]
    assert second.warnings and second.project.mappings["__last__"]["__duration_unit"] == "minutes"
    errors = [issue for issue in validate(second.project) if issue.severity == "error"]
    assert any({"a", "b"} <= set(issue.operation_ids) for issue in errors), errors
    assert second.project.scenario.placements["a"].locked


def test_reimport_retains_unmapped_fields_but_mapped_blanks_clear_them(tmp_path):
    path = tmp_path / "erp.csv"
    project = import_project()
    project.machines["m"] = Resource("m", [Window(project.horizon_start, project.horizon_end)])
    project.operations["a"] = Operation("a", "J", "m", setup=120, run=60, label="keep me",
                                        due=project.horizon_end, predecessors=["missing"])
    _write_csv(path, [["a", "J", "m", "1"]])
    minimal = import_operations(project, path, MAPPING).project.operations["a"]
    assert (minimal.setup, minimal.label, minimal.due, minimal.predecessors) == (
        120, "keep me", project.horizon_end, ["missing"])
    _write_csv(path, [["a", "J", "m", "1", "", "", ""]],
               (*MAPPING.values(), "Label", "Due", "Pred"))
    cleared = import_operations(project, path, dict(MAPPING, label="Label", due="Due", predecessors="Pred"))
    assert (cleared.project.operations["a"].label, cleared.project.operations["a"].due,
            cleared.project.operations["a"].predecessors) == ("", None, [])


@pytest.mark.parametrize("value,unit,expected", [
    ("1.5", "minutes", 90), ("0.025", "hours", 90), ("0.05", "minutes", 3),
    ("1.01", "minutes", None), ("0.01666666666666666666666666667", "minutes", None),
    ("NaN", "seconds", None), ("Infinity", "seconds", None), ("-1", "seconds", None),
    ("1e3", "seconds", None), ("0", "seconds", None),
])
def test_decimal_units_are_exact_without_silent_rounding(tmp_path, value, unit, expected):
    path = tmp_path / "erp.csv"
    _write_csv(path, [["a", "J", "m", value]])
    project = import_project()
    if expected is None:
        with pytest.raises(ImportProblem):
            import_operations(project, path, MAPPING, unit)
        assert project.operations == {}
    else:
        assert import_operations(project, path, MAPPING, unit).project.operations["a"].duration == expected


@pytest.mark.parametrize("body", [
    'Op,Job,Machine,Run\na,J,m,60\na,J,m,30\n',
    'Op,Job,Machine,Run\na,J,m,60\nb,J,m,wrong\n',
    'Op,Job,Machine,Run\na,J,m\n',
    'Op,Job,Machine,Run\na,J,m,60,unexpected\n',
    'Op,Job,Machine,Run\n"unterminated,J,m,60\n',
    'Op,Job,Machine,Run\na,J,m,60\nb,J,m,\n',
    'Op,Job,Machine,Run,Run\na,J,m,60,60\n',
])
def test_corrupt_csv_import_is_atomic(tmp_path, body):
    project = import_project()
    before = copy.deepcopy(project.to_dict())
    path = tmp_path / "broken.csv"
    path.write_text(body, encoding="utf-8")
    with pytest.raises(ImportProblem):
        import_operations(project, path, MAPPING)
    assert project.to_dict() == before


def test_xlsx_formulas_cannot_masquerade_as_cached_duration(tmp_path):
    from openpyxl import Workbook
    workbook = Workbook()
    sheet = workbook.active
    sheet.append(list(MAPPING.values()))
    sheet.append(["a", "J", "m", "=30+30"])
    path = tmp_path / "formulas.xlsx"
    workbook.save(path)
    with pytest.raises(ImportProblem, match="formula"):
        read_table(path)


def test_xlsx_native_dates_and_numeric_values_import_without_locale_guessing(tmp_path):
    from openpyxl import Workbook
    workbook = Workbook()
    sheet = workbook.active
    sheet.append([*MAPPING.values(), "Due"])
    sheet.append(["a", "J", "m", 1.5, datetime(2026, 10, 5, 16, 30)])
    path = tmp_path / "values.xlsx"
    workbook.save(path)
    result = import_operations(import_project(), path, dict(MAPPING, due="Due"))
    assert result.project.operations["a"].duration == 90
    assert result.project.operations["a"].due == int(datetime(2026, 10, 5, 16, 30,
                                                            tzinfo=timezone.utc).timestamp())


@pytest.mark.parametrize("phase", ["before_backup_replace", "before_project_replace", "after_project_replace"])
def test_process_interruption_never_leaves_truncated_main_or_backup(tmp_path, phase):
    path = tmp_path / "plan.shopshift"
    project = import_project()
    project.name = "version one"
    save_project(project, path)
    project.name = "version two"
    project.mappings["__last__"] = dict(MAPPING, __duration_unit="minutes")
    save_project(project, path)
    # os._exit bypasses Python finally blocks exactly as abrupt process death
    # does. Faults occur on both sides of the atomic file-replacement boundary.
    script = '''
import os, sys
from pathlib import Path
from shopshift import storage
path, phase = Path(sys.argv[1]), sys.argv[2]
project = storage.load_project(path)
project.name = "version three"
replace = storage.os.replace
def abrupt(source, destination):
    destination = Path(destination)
    if phase == "before_backup_replace" and destination == Path(str(path) + ".bak"):
        os._exit(91)
    if phase == "before_project_replace" and destination == path:
        os._exit(91)
    replace(source, destination)
    if phase == "after_project_replace" and destination == path:
        os._exit(91)
storage.os.replace = abrupt
storage.save_project(project, path)
'''
    environment = dict(os.environ, PYTHONPATH=str(Path(__file__).resolve().parents[1] / "src"))
    process = subprocess.run([sys.executable, "-c", script, str(path), phase], env=environment,
                             capture_output=True, text=True, timeout=15)
    assert process.returncode == 91, (process.stdout, process.stderr)
    assert load_project(path).name == ("version three" if phase == "after_project_replace" else "version two")
    assert load_project(path).mappings["__last__"] == dict(MAPPING, __duration_unit="minutes")
    backup = load_project(str(path) + ".bak")
    assert backup.name == ("version one" if phase == "before_backup_replace" else "version two")


def test_corrupt_main_requires_explicit_restore_and_preserves_damaged_bytes(tmp_path):
    path = tmp_path / "plan.shopshift"
    project = import_project()
    project.name = "Known good"
    save_project(project, path)
    project.name = "Next plan"
    save_project(project, path)
    backup_path = Path(str(path) + ".bak")
    good_backup = backup_path.read_bytes()
    damaged = b'{"format":"shopshift","version":1,"project":'
    path.write_bytes(damaged)
    with pytest.raises(StorageProblem):
        load_project(path)
    with pytest.raises(StorageProblem):
        save_project(project, path)
    assert path.read_bytes() == damaged and backup_path.read_bytes() == good_backup
    restored = restore_project(backup_path, path)
    assert restored.name == "Known good" and load_project(path).name == "Known good"
    assert Path(str(path) + ".corrupt").read_bytes() == damaged


@pytest.mark.parametrize("payload", [
    b'{"format":"shopshift","format":"other","version":1,"project":{}}',
    b'{"format":"shopshift","version":NaN,"project":{}}',
    b'{"format":"shopshift","version":2,"project":{}}',
    b'not json',
])
def test_corrupt_schema_load_rejected(tmp_path, payload):
    path = tmp_path / "broken.shopshift"
    path.write_bytes(payload)
    with pytest.raises(StorageProblem):
        load_project(path)


def test_snapshot_overnight_day_selection_and_formula_html_escaping(tmp_path):
    start = parse_timestamp("2026-10-05T23:30Z", "UTC")
    project = Project(name="<script>bad</script>", horizon_start=start, horizon_end=start + 86400,
                      machines={"m": Resource("m", [Window(start, start + 86400)])}, operations={
                          "=HYPERLINK(1)": Operation("=HYPERLINK(1)", "@unsafe", "m", run=5400,
                                                     label="<img src=x onerror=bad>", due=start + 3600),
                          "unscheduled": Operation("unscheduled", "J", "m", run=60),
                      })
    project.scenario.placements["=HYPERLINK(1)"] = Placement(start, True)
    csv_path, html_path = tmp_path / "plan.csv", tmp_path / "plan.html"
    export_csv(project, csv_path, day="2026-10-06")
    export_html(project, html_path, day="2026-10-06")
    with csv_path.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    assert len(rows) == 2
    assert rows[0]["operation_id"] == "'=HYPERLINK(1)"
    assert rows[0]["job"] == "'@unsafe"
    assert rows[0]["late_seconds"] == "1800"
    assert rows[1]["status"] == "UNSCHEDULED"
    markup = html_path.read_text(encoding="utf-8")
    assert "<script>bad</script>" not in markup and "<img src=x" not in markup
    assert "&lt;script&gt;bad&lt;/script&gt;" in markup and "&lt;img src=x" in markup
    assert "DRAFT" in markup and "late" in markup and "unscheduled" in markup
